### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Legendmanj** [DrexHD/OfflineCommands#1]
`openinv` `enderchest` `LastPos` 

please implement this, there are stuff that essentialx support for papermc server but not in essential commands, you implementing the stuff from there such as the things suggested above will really be appreciated (;

thank you

**Comment by DrexHD** [comment]
To view inventory and enderchest of offline players use [invview](https://modrinth.com/mod/invview). To get the logout position of a player you can just `/tp <offline player>`!
